apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-dev
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Du-devBR/pipelinebr-gitops.git
    targetRevision: main
    path: enviroment/dev/infra/ingress/

  destination:
    server: https://kubernetes.default.svc

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
